=== moosylog/glide/schemas/go60-layout.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MoErgo Go60 Layout",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "maxLength": 80
    },
    "combos": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "binding": {
            "$ref": "#/definitions/layoutBinding"
          },
          "keyPositions": {
            "type": "array",
            "items": {
              "type": "number",
              "minimum": 0,
              "maximum": 59
            },
            "minItems": 0,
            "maxItems": 60
          },
          "layers": {
            "type": "array",
            "items": {
              "type": "number",
              "minimum": -1
            },
            "minItems": 1,
            "if": {
              "contains": {
                "const": -1
              }
            },
            "then": {
              "maxItems": 1
            }
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64,
            "pattern": "^[a-zA-Z]\\w+$"
          },
          "requirePriorIdleMs": {
            "type": "number",
            "minimum": 1
          },
          "slowRelease": {
            "type": "boolean"
          },
          "timeoutMs": {
            "type": "number",
            "minimum": 1
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "description",
          "binding",
          "keyPositions"
        ]
      },
      "default": []
    },
    "config_parameters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "paramName": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "paramName",
          "value"
        ]
      },
      "default": []
    },
    "creator": {
      "type": "string",
      "default": "",
      "minLength": 0,
      "maxLength": 128
    },
    "custom_defined_behaviors": {
      "type": "string",
      "default": ""
    },
    "custom_devicetree": {
      "type": "string",
      "default": ""
    },
    "date": {
      "anyOf": [
        {
          "type": "number",
          "exclusiveMinimum": 0
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "firmware_api_version": {
      "type": "string",
      "default": "1",
      "minLength": 1
    },
    "holdTaps": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "maxLength": 1000
          },
          "bindings": {
            "type": "array",
            "items": [
              {
                "anyOf": [
                  {
                    "const": ""
                  },
                  {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 65,
                    "pattern": "^&[a-zA-Z]\\w*$"
                  }
                ]
              },
              {
                "anyOf": [
                  {
                    "const": ""
                  },
                  {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 65,
                    "pattern": "^&[a-zA-Z]\\w*$"
                  }
                ]
              }
            ],
            "additionalItems": false,
            "minItems": 2,
            "maxItems": 2
          },
          "descriptorId": {
            "not": {}
          },
          "flavor": {
            "type": "string",
            "enum": [
              "hold-preferred",
              "balanced",
              "tap-preferred",
              "tap-unless-interrupted"
            ]
          },
          "holdTriggerKeyPositions": {
            "type": "array",
            "items": {
              "type": "integer",
              "minimum": 0,
              "maximum": 59
            }
          },
          "holdTriggerOnRelease": {
            "type": "boolean"
          },
          "holdWhileUndecided": {
            "type": "boolean"
          },
          "holdWhileUndecidedLinger": {
            "type": "boolean"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 65,
            "pattern": "^&[a-zA-Z]\\w*$"
          },
          "quickTapMs": {
            "type": "integer",
            "minimum": -1,
            "maximum": 5000
          },
          "requirePriorIdleMs": {
            "type": "integer",
            "minimum": -1,
            "maximum": 5000
          },
          "retroTap": {
            "type": "boolean"
          },
          "tappingTermMs": {
            "type": "integer",
            "minimum": 1,
            "maximum": 5000
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "tappingTermMs",
          "bindings"
        ]
      },
      "default": []
    },
    "inputListeners": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "inputProcessors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string",
                  "minLength": 2,
                  "maxLength": 45,
                  "pattern": "^&[a-zA-Z]\\w*$"
                },
                "params": {
                  "type": "array",
                  "items": {
                    "anyOf": [
                      {
                        "type": "integer"
                      },
                      {
                        "type": "number"
                      },
                      {
                        "$ref": "#/definitions/layoutBinding"
                      },
                      {
                        "type": "array",
                        "items": {
                          "type": "string"
                        },
                        "minItems": 1
                      }
                    ]
                  },
                  "default": []
                }
              },
              "additionalProperties": false,
              "required": [
                "code"
              ]
            },
            "default": []
          },
          "nodes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "description": {
                  "type": "string",
                  "maxLength": 500
                },
                "code": {
                  "type": "string",
                  "minLength": 2,
                  "maxLength": 45,
                  "pattern": "^[a-zA-Z]\\w*$"
                },
                "inputProcessors": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 45,
                        "pattern": "^&[a-zA-Z]\\w*$"
                      },
                      "params": {
                        "type": "array",
                        "items": {
                          "anyOf": [
                            {
                              "type": "integer"
                            },
                            {
                              "type": "number"
                            },
                            {
                              "$ref": "#/definitions/layoutBinding"
                            },
                            {
                              "type": "array",
                              "items": {
                                "type": "string"
                              },
                              "minItems": 1
                            }
                          ]
                        },
                        "default": []
                      }
                    },
                    "additionalProperties": false,
                    "required": [
                      "code"
                    ]
                  },
                  "minItems": 1
                },
                "layers": {
                  "type": "array",
                  "items": {
                    "type": "integer"
                  },
                  "minItems": 1
                },
                "processNext": {
                  "type": "boolean"
                }
              },
              "additionalProperties": false,
              "required": [
                "code",
                "layers",
                "inputProcessors"
              ]
            }
          }
        },
        "additionalProperties": false,
        "required": [
          "code"
        ]
      },
      "default": []
    },
    "keyboard": {
      "type": "string",
      "const": "go60",
      "default": "go60"
    },
    "layer_names": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 25,
        "pattern": "^\\w+$"
      },
      "maxItems": 32
    },
    "layers": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "allOf": [
            {
              "$ref": "#/definitions/__schema0"
            },
            {
              "type": "object",
              "properties": {
                "decoration": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 250
                    },
                    "_uids": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "background": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "color": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "icon": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 75
                    },
                    "label": {
                      "type": "string",
                      "maxLength": 30
                    }
                  }
                }
              }
            }
          ]
        },
        "minItems": 60,
        "maxItems": 60
      },
      "maxItems": 32
    },
    "layout_parameters": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "default": {},
      "propertyNames": {
        "type": "string"
      }
    },
    "locale": {
      "type": "string",
      "default": "en-US"
    },
    "macros": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "maxLength": 1000
          },
          "bindings": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/layoutBinding"
            },
            "minItems": 1,
            "maxItems": 256
          },
          "descriptorId": {
            "not": {}
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 65,
            "pattern": "^&[a-zA-Z]\\w*$"
          },
          "params": {
            "type": "array",
            "items": {}
          },
          "tapMs": {
            "type": "integer",
            "minimum": 0
          },
          "waitMs": {
            "type": "integer",
            "minimum": 0
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "bindings"
        ]
      },
      "default": []
    },
    "modMorphs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "maxLength": 1000
          },
          "cases": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "binding": {
                  "$ref": "#/definitions/layoutBinding"
                },
                "keepMods": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "mods": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false,
              "required": [
                "binding"
              ]
            },
            "minItems": 2
          },
          "descriptorId": {
            "not": {}
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 65,
            "pattern": "^&[a-zA-Z]\\w*$"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "cases"
        ]
      },
      "default": []
    },
    "notes": {
      "type": "string",
      "maxLength": 400000
    },
    "parent_uuid": {
      "type": "string",
      "default": ""
    },
    "stickyKeys": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "maxLength": 1000
          },
          "bindings": {
            "type": "array",
            "items": [
              {
                "anyOf": [
                  {
                    "const": ""
                  },
                  {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 65,
                    "pattern": "^&[a-zA-Z]\\w*$"
                  }
                ]
              }
            ],
            "additionalItems": false,
            "minItems": 1,
            "maxItems": 1
          },
          "descriptorId": {
            "not": {}
          },
          "ignoreModifiers": {
            "type": "boolean"
          },
          "lazy": {
            "type": "boolean"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 65,
            "pattern": "^&[a-zA-Z]\\w*$"
          },
          "quickRelease": {
            "type": "boolean"
          },
          "releaseAfterMs": {
            "type": "integer",
            "minimum": 1,
            "maximum": 60000
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "bindings"
        ]
      },
      "default": []
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 2,
        "maxLength": 25,
        "pattern": "^[a-z][a-z\\-0-9]+$"
      }
    },
    "tapDances": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "maxLength": 1000
          },
          "bindings": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/layoutBinding"
            },
            "minItems": 2,
            "maxItems": 5
          },
          "descriptorId": {
            "not": {}
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 65,
            "pattern": "^&[a-zA-Z]\\w*$"
          },
          "tappingTermMs": {
            "type": "integer",
            "minimum": 1,
            "maximum": 5000
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "tappingTermMs",
          "bindings"
        ]
      },
      "default": []
    },
    "unlisted": {
      "type": "boolean",
      "default": false
    },
    "uuid": {
      "type": "string",
      "default": ""
    },
    "version": {
      "type": "integer",
      "minimum": 1,
      "maximum": 2
    }
  },
  "required": [
    "layer_names",
    "layers"
  ],
  "definitions": {
    "__schema0": {
      "type": "object",
      "properties": {
        "params": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/definitions/__schema0"
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        }
      }
    },
    "layoutBinding": {
      "type": "object",
      "properties": {
        "decoration": {},
        "params": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "$ref": "#/definitions/layoutBinding"
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "value": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== moosylog/glide/nightly/tests/fixtures/go60-touchpads-clickmap.json
{
  "version": 2,
  "keyboard": "go60",
  "firmware_api_version": "1",
  "locale": "en-US",
  "uuid": "",
  "parent_uuid": "d1380eff-30da-480f-ad0d-6f068344c165",
  "unlisted": false,
  "date": 1753145284,
  "creator": "moosy",
  "title": "Factory Default Layout",
  "notes": "Factory default layout for Go60\n\nThis layout is designed as a low-friction layout for beginners, mostly avoiding the use of hold-taps and other timing-dependent behaviours. \n\nThe layout has 5 layers:\n- Layer 0 (Base Layer): The alphas and numbers and base symbols\n- Layer 1 (Keypad Layer): Layer optimized for number data entry\n- Layer 2 (SymbolNav Layer): Navigation keys and symbol keys accessible via chording. Please note to simplify navigation key combos with ctrl+shift, this layer has added shift and control on the bottom row of the right hand pinky columns\n- Layer 3 (Magic Layer): Access to Go60 control functions such as RGB and Bluetooth\n- Layer 4 (Factory Test Layer): This layer is not used for normal typing; it is only for switch testing\n\nTo switch to Layer 1 (Keypad Layer), you can hold down RH C6R4 to temporarily switch into Layer 1, or double tap to persistently switch into Layer 1. You can single tap RH C6R4 to get back to the Layer 0 (Base Layer).\nTo switch to Layer 2 (SymbolNav Layer), you can hold down LH T1 to temporarily switch into Layer 2, or double tap to persistently switch into Layer 2. You can single tap LH T1 to get back to the Layer 0 (Base Layer).\n\nThe Right Trackpad mouse movement is accelerated 3 times the normal speed in the SymbolNav Layer (i.e. with LH T1 held).",
  "tags": [
    "qwerty"
  ],
  "custom_defined_behaviors": "",
  "custom_devicetree": "",
  "config_parameters": [],
  "layout_parameters": {
    "cirque_touch_sensitivity": ""
  },
  "layer_names": [
    "Base",
    "Keypad",
    "SymbolNav",
    "Magic",
    "Factory"
  ],
  "layers": [
    [
      {
        "value": "&kp",
        "params": [
          {
            "value": "EQUAL"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N1"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N2"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N3"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N4"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N5"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N6"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N7"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N8"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N9"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N0"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "MINUS"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "TAB"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "Q"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "W"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "E"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "R"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "T"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "Y"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "U"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "I"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "O"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "P"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "BSLH"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "ESC"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "A"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "S"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "D"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "F"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "G"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "H"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "J"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "K"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "L"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "SEMI"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "SQT"
          }
        ]
      },
      {
        "value": "&magic"
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "Z"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "X"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "C"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "V"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "B"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "N"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "M"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "COMMA"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "DOT"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "FSLH"
          }
        ]
      },
      {
        "value": "&layer",
        "params": [
          {
            "value": 1
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "GRAVE"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "DEL"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "BSPC"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "LGUI"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "LBKT"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "RBKT"
          }
        ]
      },
      {
        "value": "&layer",
        "params": [
          {
            "value": 2
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "LSHFT"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "LCTRL"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "LALT"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "SPACE"
          }
        ]
      },
      {
        "value": "&mt",
        "params": [
          {
            "value": "RALT"
          },
          {
            "value": "RET"
          }
        ]
      }
    ],
    [
      {
        "value": "&none"
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "F1"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "F2"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "F3"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "F4"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "F5"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
            "value": "F6"
          }
        ]
      },
      {
        "value": "&kp",
        "params": [
          {
